# Generated by Django 4.1.1 on 2024-05-14 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='eaa9dd9b', max_length=8, unique=True)),
                ('name_first', models.CharField(blank=True, max_length=50, null=True)),
                ('name_last', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('verify_code', models.CharField(blank=True, max_length=15, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('message_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ids', models.CharField(blank=True, max_length=50, null=True)),
                ('SYMBOL', models.CharField(choices=[('EUR/USD', 'EUR/USD'), ('USD/JPY', 'USD/JPY'), ('XAU/USD', 'XAU/USD'), ('GBP/USD', 'GBP/USD')], max_length=10)),
                ('TYPE', models.CharField(choices=[('BUY_ENTRY', 'BUY_ENTRY'), ('BUY_EXIT', 'BUY_EXIT'), ('SELL_ENTRY', 'SELL_ENTRY'), ('SELL_EXIT', 'SELL_EXIT')], max_length=10)),
                ('QUANTITY', models.PositiveIntegerField(blank=True, null=True)),
                ('ENTRY_PRICE', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('EXIT_PRICE', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cumulative_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
